name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    
  workflow_dispatch:

permissions:
  contents: write   
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          cd examples
          moon update
          moon build

      - name: Copy example games
        run: |
          python3 publish.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: page
