name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    
  workflow_dispatch:

permissions:
  contents: write   
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd examples
          moon build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
